---
- name: Shutting down firewalld
  systemd: name=firewalld state=stopped enabled=no

- name: Shutting down selinux
  shell: sed -ri "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/selinux/config

- name: Shutting down swap
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: Shutting down the NetworkManager
  systemd: name=NetworkManager state=stopped enabled=no

- name: Replace dns settings
  copy: src=/etc/resolv.conf dest=/etc/resolv.conf
  tags: testdns

- name: Shutting down selinux and swap off immediately 
  shell: setenforce 0 && swapoff -a
  ignore_errors: yes

- name: Adjusting the time zone
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: Dispatching /etc/hosts 
  copy: src=hosts dest=/etc/hosts

- name: Syncing up the time with time.windows.com
  shell: ntpdate time.windows.com

- name: Installing sshpass
  yum: name=sshpass state=present

- name: Copying scripts to the cluster
  copy: src=ssh-login-withoutpass.sh dest=/tmp/

- name: Runing the scripts to implement login with password
  shell: bash /tmp/ssh-login-withoutpass.sh
